spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.5.3/dubbo?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: rw_user
    password: shihuai1993A

dubbo:
  registry:
    #注册地址 http://127.0.0.1:80
    address: zookeeper://192.168.5.3:2181
