dubbo:
  version: 1.0.0
  application:
    id: spring-provider
    #给provider起名称
    name: dubbo-provider
  registry:
    protocol: zookeeper
  protocol:
    #dubbo协议
    name: dubbo
    #端口
    port: 20880
  scan:
    base-packages: top.inson.dubbo.service
  #提供者配置
  provider:
    name: dubbo
    protocol: dubbo
    version: 1.0.0
    timeout: 30000
