spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://10.10.21.89:3307/dubbo?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#日志打印配置
logging:
  level:
    root: info
  #file: logs/dubbo-provider/dubbo-provider.log