spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://10.10.20.199:3307/dubbo?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

dubbo:
  registry:
    #注册地址 http://127.0.0.1:80
    address: zookeeper://10.10.20.89:2181
