spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://10.10.20.199:3307/dubbo?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

dubbo:
  registry:
    #注册地址
    address: 10.10.20.199:2181

#日志打印配置
#logging:
#  level:
#    root: info
  #file: logs/dubbo-provider/dubbo-provider.log