dubbo:
  application:
    id: spring-consumer
    name: spring-consumer

  protocol:
    #dubbo协议
    name: dubbo
    #端口
    port: 20880
  registry:
    protocol: zookeeper
    address: 10.10.20.199:2181
  #消费者配置
  consumer:
    version: 1.0.0
    check: false
    timeout: 8000
