server:
  port: 9980
  servlet:
    context-path: /dubbo-consumer

spring:
  profiles:
    active: @profiles.active@
    include: consumer
  application:
    name: spring-consumer

logging:
  config: classpath:logback-black.xml
